### PR TITLE
Enable unit test execution from `npm test`

### PR DESCRIPTION
**Pull request by hideya**
This PR let `npm test` run the unit tests after performing all the necessary initializations.
CocoaPods is now used to initialize the test environment.

@rmg , would you please integrate it into the CI environment?

### CODE REVIEW

**Comment by bajtos** [comment]
@hideya the patch looks mostly good to me, however the new `npm test` command fails on our CI:

```
Loading LoopBack app "/Users/jenkins/build/workspace/loopback-sdk-ios-codegen/7d3ec467/test-env/server/server"
Generating iOS models with prefix "XX"

ERROR: Cannot call method 'replace' of undefined

test-env/bin/run-unittests: line 17: pod: command not found
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

Could you PTAL?

**Comment by hideya** [comment]
@bajtos thanks for trying it out on the CI!

There seems three issues to fix:
1) A failure in `lb-ios`
2) `lb-ios` is not exiting with non-zero exit code when an error happens
3) CocoaPods is not installed on the CI, or not visible from the `run-unittests` script

As to 1), would you please try the latest PR?
I just pushed a change to invoke `lb-ios` script with `-v` option, so that we see the call stack for `ERROR: Cannot call method 'replace' of undefined`.  Would you try it and tell me the call stack for the error?
BTW, did you ever have a chance to try `npm test` on your Mac?

As to 2), I'll work on fixing it.

As to 3), would you check if CocoaPods is installed and usable on CI?

**Comment by rmg** [comment]
@slnode test please (I've installed cocoapods)

**Comment by rmg** [comment]
@hideya our CI is running XCode 5.1, so it only has the iPhone simulator for 6.1. Any chance this can be made to work with the older XCode?

**Comment by hideya** [comment]
@rmg thank you for installing cocoapods and making the test auto-runnable.  Thanks to that, now I'm trying and debugging the test script :-)

As to Xcode version, the same Xcode test command line doesn't seem to be applicable to both Xcode 5.1.1 (on CI) and 7.1 (the latest).  Would it ever be possible to update CI's Xcode?  (Xcode 5.1 is one and half years old)

I also tried to change the Xcode test configuration to run on CI only, but not successful so far (failing to specify the test destination device).  So, I thought to follow what loopback-sdk-ios does and checked console output for a PR's automated build, but couldn't find a command line for `xcodebuild`'s test execution.
http://ci.strongloop.com/job/loopback-sdk-ios/134/consoleFull
Is there anywhere else I should check out to see the command line?  (or, loopback-sdk-ios is not actually running the unit tests on CI, do you know?)

**Comment by rmg** [comment]
@hideya loopback-sdk-ios is not running any tests :-(

The problem with upgrading is this is a remotely administered machine and I'm a little nervous about upgrading the OS over VNC :-/

**Comment by hideya** [comment]
@rmg I see.  I think I figured out a way to run the unit test on both CI and my dev machine using the same script.  I'll keep working on it.

**Comment by hideya** [comment]
@rmg @bajtos  I've managed to run the unit tests on CI (there were trickiness here and there because of the difference in the Xcode versions).  Would you please review the changes?

I had to recreate the test environment using Xcode 5 (this is the reason of trashing the old test env and adding a new one).

**Comment by bajtos** [comment]
Great work, @hideya. The patch LGTM :+1: 

@rmg what's your opinion? Would you like to review it too, or should I land it as it is?

**Comment by rmg** [comment]
LGTM, :shipit:!

**Pull request merged**
